### ISSUE TITLE
Provider equivalent for signInWithWebUI

### ISSUE THREAD

**Issue by dawidhyzy** [aws-amplify/amplify-android#2967]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```toml
// Put output below this line
amplify = "2.25.1"

amplifyframework-core = { module = "com.amplifyframework:core-kotlin", version.ref = "amplify" }
amplifyframework-aws-auth-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "amplify" }
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.12 (JetBrains s.r.o. 17.0.12+1-b1207.37)
Daemon JVM:    /Users/dawidhyzy/Library/Java/JavaVirtualMachines/jbr-17.0.12-1/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 15.1.1 aarch64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://github.com/aws-amplify/amplify-android/tree/main/aws-auth-cognito

### Describe the feature request

How can I specify a custom provider when using `Amplify.Auth.signInWithWebUI`?
This is what our web client does:

```js
    await signInWithRedirect({
      provider: { custom: "XYZ" },
    });
```

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>
